luminartech/helm-charts-public

- charts/common-gitops/Chart.yaml
Release common-gitops chart - 1.0.0
> Release common-gitops chart - 1.0.0

- .gitignore
- charts/crossplane-aws-apigateway/.helmignore
- charts/crossplane-aws-apigateway/Chart.yaml
- charts/crossplane-aws-apigateway/Makefile
- charts/crossplane-aws-apigateway/README.md
- charts/crossplane-aws-apigateway/templates/apikey.yaml
- charts/crossplane-aws-apigateway/templates/authorizer.yaml
- charts/crossplane-aws-apigateway/templates/basepathmapping.yaml
- charts/crossplane-aws-apigateway/templates/deployment.yaml
- charts/crossplane-aws-apigateway/templates/documentationpart.yaml
- charts/crossplane-aws-apigateway/templates/documentationversion.yaml
- charts/crossplane-aws-apigateway/templates/domainname.yaml
- charts/crossplane-aws-apigateway/templates/gatewayresponse.yaml
- charts/crossplane-aws-apigateway/templates/integration.yaml
- charts/crossplane-aws-apigateway/templates/integrationresponse.yaml
- charts/crossplane-aws-apigateway/templates/method.yaml
- charts/crossplane-aws-apigateway/templates/methodresponse.yaml
- charts/crossplane-aws-apigateway/templates/model.yaml
- charts/crossplane-aws-apigateway/templates/requestvalidator.yaml
- charts/crossplane-aws-apigateway/templates/resource.yaml
- charts/crossplane-aws-apigateway/templates/restapi.yaml
- charts/crossplane-aws-apigateway/templates/stage.yaml
- charts/crossplane-aws-apigateway/templates/usageplan.yaml
- charts/crossplane-aws-apigateway/templates/usageplankey.yaml
- charts/crossplane-aws-apigateway/templates/vpclink.yaml
- charts/crossplane-aws-apigateway/values-test.yaml
- charts/crossplane-aws-apigateway/values.yaml
Added crossplane-aws-apigateway
> Added crossplane-aws-apigateway

- charts/prometheus-service-discovery/.helmignore
- charts/prometheus-service-discovery/Chart.yaml
- charts/prometheus-service-discovery/Makefile
- charts/prometheus-service-discovery/README.md
- charts/prometheus-service-discovery/templates/pod-monitor.yaml
- charts/prometheus-service-discovery/templates/service-monitor.yaml
- charts/prometheus-service-discovery/values-test.yaml
- charts/prometheus-service-discovery/values.yaml
Adding prometheus-service-discovery chart
> Adding prometheus-service-discovery chart

- .github/workflows/closeissues.yaml
- .github/workflows/stale.yaml
- charts/crossplane-aws-ec2/Chart.yaml
- charts/crossplane-aws-eks/Chart.yaml
- charts/crossplane-aws-iam/Chart.yaml
- charts/crossplane-aws-kms/Chart.yaml
- charts/crossplane-aws-s3/Chart.yaml
- charts/crossplane-aws-secretsmanager/Chart.yaml
chart version: + char is not allowed by crossplane in the tags. Replaced it with char -
> chart version: + char is not allowed by crossplane in the tags. Replaced it with char -

- charts/iac/crossplane-aws-apigateway/Chart.yaml
- charts/iac/crossplane-aws-ecr/Chart.yaml
- charts/iac/crossplane-aws-efs/Chart.yaml
- charts/iac/crossplane-aws-ram/Chart.yaml
- charts/iac/crossplane-aws-route53/Chart.yaml
- charts/iac/crossplane-kubernetes/Chart.yaml
- charts/modules/apps/prometheus-service-discovery/Chart.yaml
Updated chart.yaml with correct source urls
> Updated chart.yaml with correct source urls

- charts/shared/external-service/Chart.yaml
- charts/shared/external-service/templates/ingress.yaml
- charts/shared/external-service/templates/service.yaml
Use rendering template function for values
> External-service: Use rendering template function for values

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/role-binding.yaml
- charts/shared/common-res/templates/role.yaml
Updated role and rolebinding for custom values.
> Common-res: Updated role and rolebinding for custom values.

- charts/shared/common-res/Chart.yaml
Fixed common-gitops dep chart version
> Fixed common-gitops dep chart version

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/README.md
- charts/shared/common-res/templates/cluster-role-binding.yaml
- charts/shared/common-res/templates/cluster-role.yaml
- charts/shared/common-res/values-test.yaml
- charts/shared/common-res/values.yaml
Added clusterrole and clusterrolebinding templates
> Added clusterrole and clusterrolebinding templates in common-res chart

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/cluster-role-binding.yaml
- charts/shared/common-res/templates/role-binding.yaml
Updated cluster role binding to use user provided roleref
> Updated cluster role binding to use user provided roleref

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/cluster-role-binding.yaml
- charts/shared/common-res/templates/role-binding.yaml
Removed default subjects from cluster role binding and role binding templates
> Removed default subjects from cluster role binding and role binding templates

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/README.md
- charts/shared/common-res/templates/cluster-role-binding.yaml
- charts/shared/common-res/templates/functions/podspec.tpl
- charts/shared/common-res/templates/job.yaml
- charts/shared/common-res/values-test.yaml
- charts/shared/common-res/values.yaml
Added job template and podSpec shared template in common-res
Removed default values for subjects in rolebinding
> Added job template and podSpec shared template in common-res

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
Fixed argocdsecretname name errors
> Fixed argocdsecretname name errors

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/eks-cluster-externalsecret.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
> Added refreshInterval support

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
Signed-off-by: Satish Gaikwad <satish.gaikwad@luminartech.com>
> Fixed annotations for vcluster external secret

- charts/modules/apps/external-secrets/Chart.yaml
Upgraded external-secrets upstream chart to 0.7.1
> Upgraded external-secrets upstream chart to 0.7.1

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/eks-cluster-externalsecret.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
Added support for deletionPolicy and creationPolicy values
> Added support for deletionPolicy and creationPolicy values

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/aws-externalsecret.yaml
- charts/modules/apps/external-secrets/templates/eks-cluster-externalsecret.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
Updated deletionPolicy and creationPolicy defaults
> Updated deletionPolicy and creationPolicy defaults

- charts/modules/apps/external-secrets/Chart.yaml
> External secrets - Bumping up the version

- charts/modules/apps/external-secrets/templates/aws-externalsecret.yaml
Simplified aws-externalsecrets template
> Simplified aws-externalsecrets template

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
Fixed vcluster secret decoding issue
> Fixed vcluster secret decoding issue

- charts/modules/apps/external-secrets/Chart.yaml
- charts/modules/apps/external-secrets/templates/vcluster-externalsecret.yaml
> Avoiding decoding bearerToken

- .github/workflows/helm-package-release.yaml
Release by updating the version in Chart.yaml file.
> Generate a release on version (Chart.yaml) update

- charts/shared/common-gitops/Chart.yaml
- charts/shared/common-gitops/templates/_annotations.tpl
- charts/shared/common-gitops/templates/_labels.tpl
- charts/shared/common-gitops/templates/_names.tpl
- charts/shared/common-gitops/templates/_tags.tpl
- charts/shared/common-gitops/templates/_tplvalues.tpl
- charts/shared/common-gitops/templates/crossplane/_awsDeletionPolicy.tpl
- charts/shared/common-gitops/templates/crossplane/_awsRegion.tpl
- charts/shared/common-gitops/templates/crossplane/_providerConfigRef.tpl
- charts/shared/common-gitops/templates/crossplane/_publishConnectionDetailsTo.tpl
- charts/shared/common-gitops/templates/crossplane/_reference.tpl
- charts/shared/common-gitops/templates/crossplane/_writeConnectionSecretToRef.tpl
`mergeOverwrite` overwrites parameters, while `merge` - does not.
> Replace mergeOverwrite with merge

- .github/workflows/helm-package-release.yaml
Attempt to release multiple charts at once manually fails with error:
```
/home/runner/work/_temp/94050***4f-8***4c-447c-929a-f6aa346af[49](https://github.com/luminartech/helm-charts-public/actions/runs/3951435500/jobs/6765281940#step:7:50)f.sh: line 7: [: too many arguments
```
(https://github.com/luminartech/helm-charts-public/actions/runs/3951435500/jobs/6765281940).
> Support multiple charts release at once

- .github/workflows/helm-package-release.yaml
Helm chart release action is not able to detect the updated charts correctly
Fixed chart path filter command
> Fixed chart path filter command

- charts/iac/crossplane-aws-ec2/templates/address.yaml
- charts/iac/crossplane-aws-ec2/templates/instance.yaml
- charts/iac/crossplane-aws-ec2/templates/internetgatway.yaml
- charts/iac/crossplane-aws-ec2/templates/launchtemplate.yaml
- charts/iac/crossplane-aws-ec2/templates/launchtemplateversion.yaml
- charts/iac/crossplane-aws-ec2/templates/natgateway.yaml
- charts/iac/crossplane-aws-ec2/templates/route.yaml
- charts/iac/crossplane-aws-ec2/templates/routetable.yaml
- charts/iac/crossplane-aws-ec2/templates/securitygroup.yaml
- charts/iac/crossplane-aws-ec2/templates/subnet.yaml
- charts/iac/crossplane-aws-ec2/templates/transitgateway-vpc-attachment-accepter.yaml
- charts/iac/crossplane-aws-ec2/templates/transitgateway.yaml
- charts/iac/crossplane-aws-ec2/templates/transitgatewayroute.yaml
- charts/iac/crossplane-aws-ec2/templates/transitgatewayroutetable.yaml
- charts/iac/crossplane-aws-ec2/templates/transitgatewayvpcattachment.yaml
- charts/iac/crossplane-aws-ec2/templates/volume.yaml
- charts/iac/crossplane-aws-ec2/templates/vpc.yaml
- charts/iac/crossplane-aws-ec2/templates/vpccidrblock.yaml
- charts/iac/crossplane-aws-ec2/templates/vpcendpoint.yaml
- charts/iac/crossplane-aws-ec2/templates/vpcendpointserviceconfiguration.yaml
- charts/iac/crossplane-aws-ec2/templates/vpcpeeringconnection.yaml
Sometimes forProvider is left empty and it's supposed to be supported.
> Support empty forProvider

- .github/workflows/helm-package-release.yaml
Small fix for https://github.com/luminartech/helm-charts-public/actions/runs/4016492255/jobs/6899592430#step:7:114
> Small fix in release script

- charts/iac/crossplane-aws-ec2/Chart.yaml
- charts/iac/crossplane-aws-ec2/values-test.yaml
Depends on https://github.com/luminartech/helm-charts-public/pull/49.
> Release crossplane-aws-ec2 with support of subnetCidr template

- charts/iac/crossplane-aws-rds/Chart.yaml
- charts/iac/crossplane-aws-rds/README.md
- charts/iac/crossplane-aws-rds/templates/cluster.yaml
- charts/iac/crossplane-aws-rds/templates/clusteractivitystream.yaml
- charts/iac/crossplane-aws-rds/templates/clusterendpoint.yaml
- charts/iac/crossplane-aws-rds/templates/clusterinstance.yaml
- charts/iac/crossplane-aws-rds/templates/clusterparametergroup.yaml
- charts/iac/crossplane-aws-rds/templates/clusterroleassociation.yaml
- charts/iac/crossplane-aws-rds/templates/clustersnapshot.yaml
- charts/iac/crossplane-aws-rds/templates/dbinstanceautomatedbackupsreplication.yaml
- charts/iac/crossplane-aws-rds/templates/dbsnapshotcopy.yaml
- charts/iac/crossplane-aws-rds/templates/eventsubscription.yaml
- charts/iac/crossplane-aws-rds/templates/instance.yaml
- charts/iac/crossplane-aws-rds/templates/instanceroleassociation.yaml
- charts/iac/crossplane-aws-rds/templates/optiongroup.yaml
- charts/iac/crossplane-aws-rds/templates/parametergroup.yaml
- charts/iac/crossplane-aws-rds/templates/proxy.yaml
- charts/iac/crossplane-aws-rds/templates/proxydefaulttargetgroup.yaml
- charts/iac/crossplane-aws-rds/templates/proxyendpoint.yaml
- charts/iac/crossplane-aws-rds/templates/proxytarget.yaml
- charts/iac/crossplane-aws-rds/templates/securitygroup.yaml
- charts/iac/crossplane-aws-rds/templates/snapshot.yaml
- charts/iac/crossplane-aws-rds/templates/standardssubscription.yaml
- charts/iac/crossplane-aws-rds/templates/subnetgroup.yaml
- charts/iac/crossplane-aws-rds/values-test.yaml
- charts/iac/crossplane-aws-rds/values.yaml
Convert crossplane-aws-rds chart to upbound aws provider.
> Switch RDS chart to upbound aws provider

- charts/iac/crossplane-aws-iam/Chart.yaml
- charts/iac/crossplane-aws-iam/values-test.yaml
- charts/iac/crossplane-aws-kms/Chart.yaml
- charts/iac/crossplane-aws-s3/Chart.yaml
- charts/shared/common-gitops/Chart.yaml
- charts/shared/common-gitops/templates/crossplane/_awsPolicy.tpl
See values-test.yaml for examples and _awsPolicy.tpl for explanation.
> Add support of raw and list formats of IAM policies

- charts/modules/apps/external-secrets/Chart.yaml
Update external-secret's dependencies to make use of new IAM policy document
> Update external-secret's dependencies

- charts/iac/crossplane-aws-elasticache/.helmignore
- charts/iac/crossplane-aws-elasticache/Chart.yaml
- charts/iac/crossplane-aws-elasticache/Makefile
- charts/iac/crossplane-aws-elasticache/README.md
- charts/iac/crossplane-aws-elasticache/templates/cluster.yaml
- charts/iac/crossplane-aws-elasticache/templates/parametergroup.yaml
- charts/iac/crossplane-aws-elasticache/templates/replicationgroup.yaml
- charts/iac/crossplane-aws-elasticache/templates/subnetgroup.yaml
- charts/iac/crossplane-aws-elasticache/templates/user.yaml
- charts/iac/crossplane-aws-elasticache/templates/usergroup.yaml
- charts/iac/crossplane-aws-elasticache/values-test.yaml
- charts/iac/crossplane-aws-elasticache/values.yaml
- Add crossplane-aws-elasticache chart
- Update docs
> Add crossplane-aws-elasticache helm chart

- charts/iac/crossplane-kubernetes/Chart.yaml
- charts/iac/crossplane-kubernetes/README.md
- charts/iac/crossplane-kubernetes/templates/object.yaml
- charts/iac/crossplane-kubernetes/templates/provider-config.yaml
- charts/iac/crossplane-kubernetes/values-test.yaml
- charts/iac/crossplane-kubernetes/values.yaml
- charts/modules/infra/aws-eks-rbac/Chart.yaml
- charts/modules/infra/aws-eks-rbac/README.md
- Rename awsDeletionPolicy to deletionPolicy
- Add support of providerConfig to make chart comply with other IAC charts design
- Extend the Object template
- Update crossplane chart version
> Update crossplane-kubernetes chart

- charts/iac/crossplane-aws-cloudwatchevents/Chart.yaml
- charts/iac/crossplane-aws-cloudwatchevents/templates/bus-policy.yaml
We want policy to be a string.
> fix(aws-cloudwatchevents): small fix

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/configmap.yaml
- charts/shared/common-res/templates/deployment.yaml
- charts/shared/common-res/templates/endpoint.yaml
- charts/shared/common-res/templates/horizontal-pod-autoscaler.yaml
- charts/shared/common-res/templates/ingress.yaml
- charts/shared/common-res/templates/job.yaml
- charts/shared/common-res/templates/persistent-volume-claim.yaml
- charts/shared/common-res/templates/pod.yaml
- charts/shared/common-res/templates/role-binding.yaml
- charts/shared/common-res/templates/role.yaml
- charts/shared/common-res/templates/secret.yaml
- charts/shared/common-res/templates/service-account.yaml
- charts/shared/common-res/templates/service.yaml
- charts/shared/common-res/values-test.yaml
Allow to override namespace for common-res resources.
> feat(common-res): Allow to override namespace

- charts/modules/apps/argo-workflows/Chart.yaml
- charts/modules/apps/argo-workflows/templates/cluster-workflow-template.yaml
- charts/modules/apps/argo-workflows/templates/cron-workflow.yaml
- charts/modules/apps/argo-workflows/templates/workflow-template.yaml
- charts/modules/apps/argo-workflows/templates/workflow.yaml
- charts/modules/apps/argo-workflows/values-test.yaml
- charts/modules/apps/argo-workflows/values.yaml
Make it possible to control `*Workflow*` CRDs from values.yaml.
> feat(argo-workflows): Initial support of managing resources from values.yaml

- charts/iac/crossplane-aws-cloudwatch/Chart.yaml
- charts/iac/crossplane-aws-cloudwatch/templates/MetricAlarm.yaml
- charts/iac/crossplane-aws-cloudwatch/templates/MetricStream.yaml
**Why this change?**
Bad "policy" field in the template.
> CloudWatch Module

- charts/modules/apps/monitoring/.helmignore
- charts/modules/apps/monitoring/Chart.yaml
- charts/modules/apps/monitoring/Makefile
- charts/modules/apps/monitoring/README.md
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/argocd-basic.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/cert-manager.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/crossplane.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/external-dns.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/karpenter-capacity.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/karpenter-performance.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/loki.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/nginx-ingress.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/nvidia-dcgm.yaml
- charts/modules/apps/monitoring/templates/grafana/dashboards-1.14/trivy-vulnerabilities.yaml
- charts/modules/apps/monitoring/templates/slack-templates.yaml
- charts/modules/apps/monitoring/utils/grafana-dashboards/argocd-basic.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/cert-manager.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/crossplane.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/external-dns.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/karpenter-capacity.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/karpenter-performance.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/loki.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/nginx-ingress.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/nvidia-dcgm.json
- charts/modules/apps/monitoring/utils/grafana-dashboards/trivy-vulnerabilities.json
- charts/modules/apps/monitoring/utils/sync_grafana_dashboards.py
- charts/modules/apps/monitoring/values-test.yaml
- charts/modules/apps/monitoring/values.yaml
> feat(monitoring): Init helm chart

- charts/iac/crossplane-aws-sns/Chart.yaml
- charts/iac/crossplane-aws-sns/templates/topic-policy.yaml
**Why this change?**
To enable yaml format for sns resource policy
> sns-policy-yaml

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/cluster-role-binding.yaml
- charts/shared/common-res/templates/cluster-role.yaml
- charts/shared/common-res/templates/configmap.yaml
- charts/shared/common-res/templates/deployment.yaml
- charts/shared/common-res/templates/endpoint.yaml
- charts/shared/common-res/templates/horizontal-pod-autoscaler.yaml
- charts/shared/common-res/templates/ingress.yaml
- charts/shared/common-res/templates/job.yaml
- charts/shared/common-res/templates/persistent-volume-claim.yaml
- charts/shared/common-res/templates/persistent-volume.yaml
- charts/shared/common-res/templates/pod.yaml
- charts/shared/common-res/templates/role.yaml
- charts/shared/common-res/templates/secret.yaml
- charts/shared/common-res/templates/service-account.yaml
- charts/shared/common-res/templates/service.yaml
- charts/shared/common-res/templates/storageclass.yaml
Add support of new ItemID function to common-res (https://github.com/luminartech/helm-charts-public/pull/174).
> feat(common-res): Update dependency on common-gitops

- charts/iac/crossplane-aws-iam/Chart.yaml
- charts/iac/crossplane-aws-iam/templates/access-key.yaml
- charts/iac/crossplane-aws-iam/templates/account-alias.yaml
- charts/iac/crossplane-aws-iam/templates/account-password-policy.yaml
- charts/iac/crossplane-aws-iam/templates/group-membership.yaml
- charts/iac/crossplane-aws-iam/templates/group-policy-attachment.yaml
- charts/iac/crossplane-aws-iam/templates/group.yaml
- charts/iac/crossplane-aws-iam/templates/instance-profile.yaml
- charts/iac/crossplane-aws-iam/templates/openid-connect-provider.yaml
- charts/iac/crossplane-aws-iam/templates/policy.yaml
- charts/iac/crossplane-aws-iam/templates/role-policy-attachment.yaml
- charts/iac/crossplane-aws-iam/templates/role.yaml
- charts/iac/crossplane-aws-iam/templates/saml-provider.yaml
- charts/iac/crossplane-aws-iam/templates/server-certificate.yaml
- charts/iac/crossplane-aws-iam/templates/service-linked-role.yaml
- charts/iac/crossplane-aws-iam/templates/service-specific-credential.yaml
- charts/iac/crossplane-aws-iam/templates/signing-certificate.yaml
- charts/iac/crossplane-aws-iam/templates/user-group-membership.yaml
- charts/iac/crossplane-aws-iam/templates/user-login-profile.yaml
- charts/iac/crossplane-aws-iam/templates/user-policy-attachment.yaml
- charts/iac/crossplane-aws-iam/templates/user-ssh-key.yaml
- charts/iac/crossplane-aws-iam/templates/user.yaml
- charts/iac/crossplane-aws-iam/templates/virtual-mfa-device.yaml
Utilize function from https://github.com/luminartech/helm-charts-public/pull/173 in one IAC module in order to gain support of templates in enabled field as well as make that logic easily configurable and DRY the code.
> feat(crossplane-aws-iam): Update in order to gain support of improved enable condition logic

- charts/shared/common-gitops/Chart.yaml
- charts/shared/common-gitops/templates/_yamlToJson.tpl
Function to convert Yaml in charts into JSON string when it is required by spec
> Add Yaml To JSON function into common-gitops

- charts/iac/crossplane-aws-dynamodb/.helmignore
- charts/iac/crossplane-aws-dynamodb/Chart.yaml
- charts/iac/crossplane-aws-dynamodb/Makefile
- charts/iac/crossplane-aws-dynamodb/README.md
- charts/iac/crossplane-aws-dynamodb/templates/contributorinsights.yaml
- charts/iac/crossplane-aws-dynamodb/templates/globaltable.yaml
- charts/iac/crossplane-aws-dynamodb/templates/kinesisstreamingdestination.yaml
- charts/iac/crossplane-aws-dynamodb/templates/table.yaml
- charts/iac/crossplane-aws-dynamodb/templates/tableitem.yaml
- charts/iac/crossplane-aws-dynamodb/templates/tablereplica.yaml
- charts/iac/crossplane-aws-dynamodb/templates/tag.yaml
- charts/iac/crossplane-aws-dynamodb/values-test.yaml
- charts/iac/crossplane-aws-dynamodb/values.yaml
Based on https://marketplace.upbound.io/providers/upbound/provider-aws/v0.41.0/managed-resources?query=dynamodb
> Add crossplane-aws-dynamodb chart

- charts/modules/apps/crossplane/Chart.yaml
- charts/modules/apps/crossplane/README.md
- charts/modules/apps/crossplane/values.yaml
See https://github.com/crossplane-contrib/provider-kubernetes/issues/183#issue-2095403251
> IPE-1714: Avoid using kubernetes as a name for kubernetes provider

- charts/modules/apps/loki-scalable/Chart.yaml
- charts/modules/apps/loki-scalable/README.md
- charts/modules/apps/loki-scalable/values.yaml
- Promtail is daemonset and should run on all nodes
- The toleration defined in this this PR will match all keys, values and effect. Hence, promtail will tolerate all taints.
- Here is example of kube-proxy daemonset spec
`# k get ds kube-proxy -o=jsonpath='{.spec.template.spec.tolerations}'`
`[{"operator":"Exists"}]`
> promtail-daemonset-tolerate-all-taints

- README.md
> SW-9412: Fix README.md

- charts/modules/apps/monitoring/Chart.yaml
- charts/modules/apps/monitoring/README.md
- charts/modules/apps/monitoring/values.yaml
> SW-10435-organize-default-dashboards

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/README.md
- charts/shared/common-res/templates/statefulset.yaml
- charts/shared/common-res/values.yaml
Added statefulset in common-res chart
> Added statefulset in common-res chart

- charts/modules/apps/chatbot-ui/Chart.yaml
Fixed typo in the chatbot ui chart.yaml file
> Fixed typo in the chatbot ui chart.yaml file

- charts/modules/apps/monitoring/Chart.yaml
- charts/modules/apps/monitoring/README.md
- charts/modules/apps/monitoring/values.yaml
> Crossplane-External-Name

- charts/modules/apps/monitoring/Chart.yaml
- charts/modules/apps/monitoring/README.md
- charts/modules/apps/monitoring/values.yaml
- Crossplane External name not required for AWS secrets
> SW-9245-secret-crossplane-external-name

- charts/modules/apps/devspace/Chart.yaml
- charts/modules/apps/devspace/values.yaml
- charts/shared/common-res/Chart.yaml
Added dind support for devspace pod
> Added dind support for devspace pod

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/README.md
- charts/modules/infra/aws-eks/values.yaml
SW-6513: Updated EKS helm chart to use 1.29 kubernetes version
> SW-6513: Updated EKS helm chart to use 1.29 kubernetes version

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/values.yaml
- Update the CNI and CSI addons
> SW-7794-upgrade-eks-mgmt-cluster-addons

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/values.yaml
- Migrate kube-proxy to EKS Addon
> SW-7794-upgrade-kube-proxy-migrate-eks-addon

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/values.yaml
> SW-7794-upgrade-cni-csi-latest

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/README.md
- charts/modules/infra/aws-eks/values.yaml
> SW-7794-resolve-conflicts-error

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/README.md
- charts/modules/infra/aws-eks/values.yaml
> change resolve for update

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/values.yaml
Set the resolve conflict in upper layer charts when needed.
> SW-7794-resolve-conflicts-error-set-in-higher-chart

- charts/modules/apps/devspace/Chart.yaml
- charts/modules/apps/devspace/values.yaml
Updated helm chart to define resources at global level
> Updated devspace helm chart to define resources at global level

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/service.yaml
Common-res chart: Updated service specs to include missing keys
> Common-res chart: Updated service specs to include missing keys

- charts/modules/apps/monitoring/Chart.yaml
- Update Grafana and prom stack.
> SW-8943-grafana-update-for-okta

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/README.md
- charts/modules/infra/aws-eks/values.yaml
> SW-7796-upgrade-lum-cluster-kube-proxy

- charts/modules/apps/cost-analyzer/Chart.yaml
> Upgrade kubecost

- charts/modules/apps/chatbot-ui/Chart.yaml
- charts/modules/apps/chatbot-ui/README.md
- charts/modules/apps/chatbot-ui/values.yaml
- Change policy to always because the upstream image does not publish tags.
> chatbot-ui-update

- charts/modules/apps/osrm-nominatim/Chart.yaml
> osrm-nominatim-chart-version

- charts/modules/apps/osrm-nominatim/Chart.yaml
- charts/modules/apps/osrm-nominatim/values-test.yaml
- charts/modules/apps/osrm-nominatim/values.yaml
> osrm-nominatim-update-chart

- charts/modules/apps/osrm-nominatim/Chart.yaml
- charts/modules/apps/osrm-nominatim/values.yaml
> osrm-nominatim-apache-configmap

- charts/modules/apps/osrm-nominatim/Chart.yaml
- charts/modules/apps/osrm-nominatim/values.yaml
> osrm-nominatim-update-version

- charts/modules/apps/filestash-app/Chart.yaml
- charts/modules/apps/filestash-app/README.md
- charts/modules/apps/filestash-app/values.yaml
> filestash-helm-chart-update

- charts/modules/apps/filestash-app/Chart.yaml
- charts/modules/apps/filestash-app/values.yaml
> filestash-helm-chart-cmap-fix

- charts/modules/apps/filestash-app/Chart.yaml
- charts/modules/apps/filestash-app/README.md
- charts/modules/apps/filestash-app/values.yaml
> filestash-helm-chart-port

- charts/modules/apps/filestash-app/Chart.yaml
- charts/modules/apps/filestash-app/values.yaml
Fix rolling update default values
> fix values

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/README.md
- charts/modules/infra/aws-eks/values.yaml
Enable AWS Mountpoint S3 CSI Driver Addon
> eks-addon-s3-csi

- charts/iac/crossplane-aws-iam/Chart.yaml
- charts/iac/crossplane-aws-iam/README.md
- charts/iac/crossplane-aws-iam/templates/role-policy.yaml
- charts/iac/crossplane-aws-iam/values-test.yaml
- charts/iac/crossplane-aws-iam/values.yaml
> crossplane-iam-rolepolicy

- charts/iac/crossplane-aws-iam/Chart.yaml
- charts/iac/crossplane-aws-iam/templates/role-policy.yaml
> crossplane-iam-rolepolicies

- charts/modules/infra/aws-mountpoint-s3-csi-driver/Chart.yaml
- charts/modules/infra/aws-mountpoint-s3-csi-driver/values.yaml
> eks-addon-s3-csi-namespace

- charts/modules/infra/aws-eks/Chart.yaml
- charts/modules/infra/aws-eks/values.yaml
Disable the s3 addon by default
> disable-eks-addon-s3

- charts/modules/infra/aws-mountpoint-s3-csi-driver/Chart.yaml
- charts/modules/infra/aws-mountpoint-s3-csi-driver/values-test.yaml
- charts/modules/infra/aws-mountpoint-s3-csi-driver/values.yaml
- Move Service Account annotation to values-test.yaml
- This can be specific in the Argo ApplicationSet
> eks-addon-s3-sa-annotation

- charts/shared/common-gitops/Chart.yaml
- charts/shared/common-gitops/templates/crossplane/_managementPolicies.tpl
managementPolicies field is supposed to replace deletionPolicy and allows to configure Crossplane to ignore resource updates.
> feat(common-gitops): Add support for managementPolicies

- charts/shared/common-res/Chart.yaml
- charts/shared/common-res/templates/cronjob.yaml
Update template to parse concurrencyPolicy value.
> cronjob-concurrency-policy

- charts/modules/apps/argo-cd/Chart.yaml
- charts/modules/apps/argo-cd/README.md
- charts/modules/apps/argo-cd/values.yaml
- Enabling uniform cluster sharding across Argo CD Application Controller replicas using `round-robin` algorithm.
- Refer this for supported algorithms: https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller
- Enabling Dynamic Distribution of Clusters. This is alpha feature. Refer: https://argo-cd.readthedocs.io/en/latest/operator-manual/dynamic-cluster-distribution/#dynamic-cluster-distribution
> argocd-application-controller-loadbalancing

- charts/modules/apps/crossplane/Chart.yaml
- charts/modules/apps/crossplane/values.yaml
- based on Kubecost recommendations and usage metrics
> Right-size CPU and memory requests for Crossplane

- charts/modules/apps/karpenter/Chart.yaml
- There are no breaking changes since 1.3.2
> Upgrade Karpenter from v1.3.2 to v1.5.0

- charts/modules/apps/argo-cd/Chart.yaml
- charts/modules/apps/argo-cd/README.md
- charts/modules/apps/argo-cd/values.yaml
- references:
https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.14-3.0/
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml
https://github.com/argoproj/argo-cd/releases/tag/v3.0.6
> chore: upgrade ArgoCD to v3.0.6
