luminartech/helm-charts-public

charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/_tplvalues.tpl

Tplrender template still returns `{}` even thought it's an empty value. Return "" - it will be valid in all cases.

SRE-2474: Fix tpl render template

---

charts/modules/apps/external-secrets/Chart.yaml
charts/modules/apps/external-secrets/values.yaml

Using release name for the service account. This fixes the bug with the SA name in the IAM role policy when fullNameOverride is used.

External-secrets: Use release name for service account

---

charts/iac/crossplane-aws-iam/Chart.yaml
charts/iac/crossplane-aws-iam/templates/policy.yaml
charts/iac/crossplane-aws-iam/templates/role.yaml
charts/iac/crossplane-aws-iam/values-test.yaml
charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/crossplane/_awsPolicy.tpl

Yaml:
- is easier to write, read and maintain for humans
- is shorter
- statements can be combined or overridden on different layers because they are stored as dict, not list (see values-test.yaml for an example)
- we can benefit from yaml syntax checker

Define IAM policies using Yaml, not Json/String

---

charts/iac/crossplane-aws-iam/Chart.yaml
charts/iac/crossplane-aws-iam/values-test.yaml
charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/crossplane/_awsPolicy.tpl

Rationale: Since tpl rendering happened on json, simple variable resolving like "{{ .Values.global.variable }}" worked fine, but "{{ .Values.global.variable | replace '-' '' }}" - failed.
Doing tpl rendering on raw data structure before converting it to Json allows to support latter use-case.

Support complex templating in policies

---

charts/iac/crossplane-aws-s3/Chart.yaml
charts/iac/crossplane-aws-s3/README.md
charts/iac/crossplane-aws-s3/templates/bucketIntelligenttieringconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketaccelerateconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketacl.yaml
charts/iac/crossplane-aws-s3/templates/bucketanalyticsconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketcorsconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketinventory.yaml
charts/iac/crossplane-aws-s3/templates/bucketlifecycleconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketlogging.yaml
charts/iac/crossplane-aws-s3/templates/bucketmetric.yaml
charts/iac/crossplane-aws-s3/templates/bucketnotification.yaml
charts/iac/crossplane-aws-s3/templates/bucketobject.yaml
charts/iac/crossplane-aws-s3/templates/bucketobjectlockconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketownershipcontrols.yaml
charts/iac/crossplane-aws-s3/templates/bucketpolicy.yaml
charts/iac/crossplane-aws-s3/templates/bucketpublicaccessblock.yaml
charts/iac/crossplane-aws-s3/templates/bucketreplicationconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketrequestpaymentconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketserversideencryptionconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/bucketversioning.yaml
charts/iac/crossplane-aws-s3/templates/bucketwebsiteconfiguration.yaml
charts/iac/crossplane-aws-s3/templates/object.yaml
charts/iac/crossplane-aws-s3/templates/objectcopy.yaml
charts/iac/crossplane-aws-s3/values-test.yaml
charts/iac/crossplane-aws-s3/values.yaml

Community aws provider does not seem to support buckets with disabled ACLs and upbound provider has much more features.

Migrate crossplane-aws-s3 chart to upbound provider

---

charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/crossplane/_publishConnectionDetailsTo.tpl

It's handy to be able to override the generated secret name.

Make the name of the secret returned by PublishConnectionsDetailsTo configurable

---

charts/iac/crossplane-aws-ecr/Chart.yaml

aws-ecr chart v.0.37.0-0 is stuck in limbo state. Increment the version to trigger a new release.

Trigger aws-ecr chart release

---

charts/iac/crossplane-kubernetes/Chart.yaml

Version 1.1.0 of common-gitops helm chart introduced a breaking change so it's not possible to use charts together that depend on different major releases of common-gitops.

Update crossplane-karpenter dependencies

---

charts/modules/infra/aws-eks-rbac/Chart.yaml
charts/modules/infra/aws-eks-rbac/README.md
charts/modules/infra/aws-eks-rbac/values.yaml

Syntax of ProviderConfig in crossplane-kubernetes was changed to comply with other IAC charts, i.e. ignore "spec" key. Update dependent module.

Use correct syntax for providerConfig

---

charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/_names.tpl

Rationale: need to be able to deploy arbitrary parts of application to different namespaces.

feat(common-gitops): Allow to override namespace

---

charts/modules/apps/crossplane/Chart.yaml
charts/modules/apps/crossplane/templates/provider-config.yaml
charts/modules/apps/crossplane/templates/storeconfig.yaml
charts/modules/apps/crossplane/values.yaml

- Using variables in itemIDs is not yet supported by gitops-common. Removing something that can not be used.
- Set default apiVersion for some resources to save few lines of code.

chore(crossplane): use default apiVersion for crossplane resources

---

charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/_utils.tpl

Render "enabled" value as golang template. Should still be backward compatible with existing code in values.yaml files.

feat(gitops-common): Add itemEnabled template

---

charts/modules/infra/aws-vpc/Chart.yaml
charts/modules/infra/aws-vpc/values.yaml

**What this change will do?**
This PR will protect the critical default routes from getting deleted and mark them orphan if crossplane resources are deleted.

EKS: Avoid critical VPC routes getting deleted

---

charts/modules/apps/loki-scalable/Chart.yaml
charts/modules/apps/loki-scalable/README.md
charts/modules/apps/loki-scalable/values.yaml

There is a bug in common-gitops namespace function. To unblock the promtail related change, setting the namespace to value where the chart is installed.

loki-scalable-values-fix

---

charts/shared/common-gitops/Chart.yaml
charts/shared/common-gitops/templates/crossplane/_publishConnectionDetailsTo.tpl
charts/shared/common-gitops/templates/crossplane/_writeConnectionSecretToRef.tpl

common-gitops.tplvalues.render returns null if the input is empty so it can not be used with default function

fix(common-gitops): support no input for some parameters

---

charts/modules/apps/crossplane/Chart.yaml
charts/modules/apps/crossplane/README.md
charts/modules/apps/crossplane/values.yaml

> The poll option determines how often the provider will compare the desired Workspace configuration with the actual deployed resources (terraform plan) and reconcile any differences (terraform apply). The default value is 10m. Shorter poll intervals increase the load on the provider by reconciling existing Workspaces more often to allow for faster reconciliation of differences, but this can cause the provider to take longer to process new Workspace objects that are created. Longer poll intervals will reduce the load on the provider by reconciling existing Workspaces less often, taking a longer time to identify and reconcile differences, but also shortening the amount of time required for the provider to respond to new Workspaces.
For `--sync` parameter the best explanation I could find …

feat(crossplane): Use default poll and sync intervals

---

charts/modules/apps/osrm-nominatim/values.yaml

Enable resource limits. This is important for the initialization phase.

osrm-nominatim-default-resource-limits

---

charts/modules/apps/loki-scalable/Chart.yaml
charts/modules/apps/loki-scalable/README.md
charts/modules/apps/loki-scalable/values.yaml
charts/modules/apps/monitoring/values.yaml

The goal is to add ingress to Loki's gateway with basic auth. Latter requires a secret.

feat(loki-scalable): Make it possible to store secrets for Loki in AWS SM

---

charts/modules/apps/karpenter/Chart.yaml

- Ugrade to version 1.1.4 [Refer Tags here](https://gallery.ecr.aws/karpenter/karpenter)
- Version 1.1.x removed support for v1beta1. Ensure the API was migrated to v1 before applying this upgrade.

gitops: Upgrade Karpenter from v1.0.x to v1.1.x

---

charts/modules/apps/argo-cd/Chart.yaml
charts/modules/apps/argo-cd/README.md
charts/modules/apps/argo-cd/values.yaml

- switch from round-robin to consistent-hashing algorithm for shard distribution
- upgrade ArgoCD from v7.8.2 to v7.8.12

SW-23366: Switch ArgoCD to consistent-hashing algorithm

---

charts/modules/apps/karpenter/Chart.yaml
charts/modules/apps/karpenter/values.yaml

- EBS CSI controller pod fails to acces AWS Instance Metadata Service (IMDS) and returns below error
`Could not attach volume "vol-xxxxx" to node "i-xxxxx": error listing AWS instances: operation error EC2: DescribeInstances, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded`
- Karpenter v1.0 onwards, the default value was changed to "1" https://karpenter.sh/v1.0/concepts/nodeclasses/#specmetadataoptions
- In previous version, it was "2"
https://karpenter.sh/v0.32/concepts/nodeclasses/#specmetadataoptions
- **`httpPutResponseHopLimit`** is a setting in AWS Instance Metadata Service (IMDS) that controls the number of network hops allowed for instance metadata PUT response …

Update httpPutResponseHopLimit to 2

---

charts/modules/apps/ingress-nginx/Chart.yaml

- in order to address:
> “Today, the ingress-nginx maintainers have [released patches for a batch of critical vulnerabilities](https://github.com/kubernetes/ingress-nginx/releases) that could make it easy for attackers to take over your Kubernetes cluster. If you are among the over 40% of Kubernetes administrators using [ingress-nginx](https://github.com/kubernetes/ingress-nginx/), you should take action immediately to protect your users and data.”

SW-23600: bump NGINX Helm chart to v4.12.1
